spring:
  datasource:
    url: jdbc:postgresql://restapi-test-jh.internal:5432/postgres
    username: postgres
    password: SAJYZMNUo308zMI
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false